# Generated by Django 6.0.2 on 2026-02-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="subtask",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
