# Generated by Django 6.0.2 on 2026-03-13 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="due_date",
        ),
        migrations.AddField(
            model_name="activity",
            name="work_date",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
