# Generated by Django 6.0.2 on 2026-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_activity_status_subtask_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
