# Generated by Django 6.0.2 on 2026-03-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_activity_due_date_activity_work_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="work_date",
            new_name="due_date",
        ),
    ]
