# Generated by Django 6.0.2 on 2026-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_activity_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="due_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
