# Generated by Django 6.0.2 on 2026-03-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_due_date_to_datetimefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
