# Generated by Django 6.0.2 on 2026-03-24 03:22

from django.db import migrations
def migrate_completed_to_status(apps, schema_editor):
    Subtask = apps.get_model('api', 'Subtask')
    Subtask.objects.filter(completed=True).update(status='completed')
    Subtask.objects.filter(completed=False).update(status='pending')

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subtask_note_subtask_status"),
    ]

    operations = [
        migrations.RunPython(migrate_completed_to_status),
    ]
