# Generated by Django 6.0.2 on 2026-03-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20260323_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtask",
            name="completed",
        ),
    ]
